# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9cf58a60dff02f5474484d0b1c872632b3d52bb6a7db07e31077701aab6809803b39286a2a78e3786d1695b6dd23933a6f3ea92a313c262d77177ef0512c8dcd

test:
  secret_key_base: fc0e0da1ece945a42d0d9c02d073c8cd5f5747df92f2f1d7ce1cf1bde6c8a4a9ac5adb7428666f190461687cef2c02d51d6abc3ff63f99a555f75554a53f890f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
